site_name: db2qthelp
site_url: https://github.com/dkrajzew/db2qthelp
site_description: A web type setter
site_author: Daniel Krajzewicz
docs_dir: ./mkdocs

repo_url: https://github.com/dkrajzew/db2qthelp.git
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: install.md
    - Usage: cmd.md
    - ChangeLog: changes.md
    - Legal: legal.md
    - License (BSD): https://github.com/dkrajzew/db2qthelp/blob/master/LICENSE
    - API: api.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2022-2023 Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [..]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"